# ServiceMonitor for Qdrant - Prometheus scraping config
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qdrant-monitor
  namespace: monitoring
  labels:
    app: qdrant
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qdrant
  namespaceSelector:
    matchNames:
      - qdrant
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s

